### ISSUE TITLE
Wouldn't it be better to suggest putting these in /etc/systemd/system?

### ISSUE THREAD

**Issue by murrant** [hadret/scripts-graylog2#2]
Also, your docs point to graylog2-server.service, not graylog-server.service.

**Comment by hadret** [comment]
Definitely. I shouldn't also advise to download them directly /lib/... and instead to put them under /etc/.... But just a quick question if I may -- are they still working? Cause I haven't been playing with graylog2 for a very long time :)

**Comment by murrant** [comment]
It works, fine, but you could probably use systemd to allow graylog to listen on 514 and not run as root.

**Comment by hadret** [comment]
No running as a root is valid -- should be/could be changed to whatever user you can run it from. But it depends on the deployment -- if you have separate user, just adjust the script to your needs. When it comes to listening on port 514 -- I have doubts it's a good idea for two reasons: 1. this is default port for (r)syslog(-ng); 2. if you want to run it as non-root user, you need to pick port above 1024. Not to mention, that listening on the port is set in the configuration of the application, not in the systemd script.
